name: Add issues to project

# GHA_RELEASE_TOKEN requires
# org->project: read/write
# repos->issues: read

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ${{ github.event.repository.private && 'self-hosted' || 'ubuntu-latest' }}

    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/iotaledger/projects/104
          github-token: ${{ secrets.TWIN_GHA_RELEASE_TOKEN }}
