name: Project Add Issue

# GHA_RELEASE_TOKEN requires
# org->project: read/write
# repos->issues: read

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on:
      labels: ${{ github.event.repository.private && 'self-hosted-small' || 'ubuntu-latest' }}
      group: ${{ github.event.repository.private && 'twin' || 'default' }}

    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/iotaledger/projects/104
          github-token: ${{ secrets.TWIN_GHA_RELEASE_TOKEN }}

      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TWIN_GHA_RELEASE_TOKEN }}
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['needs-triage'],
            })
